config/routes.rb
ShopShine::Application.routes.draw do

root to: 'authentications#new'

  namespace :api do
    resources :users
  end

  namespace :api do
    resources :category_sizes
  end

  namespace :api do
    resources :category
  end

  resources :authentications

  post 'users/category_sizes' => 'users#category_sizes'

  get 'users/results' => 'users#results'

  get 'users/results/:id' => 'users#results'

  get 'users/category_sizes/:categorysizeid' => 'users#show_json'

  resources :users

  get 'categories/show_json/:id' => 'categories#show_json'

  get 'signup' => 'users#new'

  resources :sizes

  resources :category_sizes

  resources :categories

  

  

end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  before_action :set_size, only: [:show, :edit, :update, :destroy]

  # GET /sizes
  # GET /sizes.json
  def index
    @sizes = Size.all
  end

  # GET /sizes/1
  # GET /sizes/1.json
  def show
  end

  # GET /sizes/new
  def new
    @size = Size.new
  end

  # GET /sizes/1/edit
  def edit
  end

  # POST /sizes
  # POST /sizes.json
  def create
    @size = Size.new(size_params)

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, notice: 'Size was successfully created.' }
        format.json { render action: 'show', status: :created, location: @size }
      else
        format.html { render action: 'new' }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sizes/1
  # PATCH/PUT /sizes/1.json
  def update
    respond_to do |format|
      if @size.update(size_params)
        format.html { redirect_to @size, notice: 'Size was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sizes/1
  # DELETE /sizes/1.json
  def destroy
    @size.destroy
    respond_to do |format|
      format.html { redirect_to sizes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_size
      @size = Size.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def size_params
      params.require(:size).permit(:name, :code, :category_id)
    end
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/sizes/_form.html.erb
<%= form_for(@size) do |f| %>
  <% if @size.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@size.errors.count, "error") %> prohibited this size from being saved:</h2>

      <ul>
      <% @size.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sizes/edit.html.erb
<h1>Editing size</h1>

<%= render 'form' %>

<%= link_to 'Show', @size %> |
<%= link_to 'Back', sizes_path %>

app/views/sizes/index.html.erb
<h1>Listing sizes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sizes.each do |size| %>
      <tr>
        <td><%= size.name %></td>
        <td><%= size.code %></td>
        <td><%= size.category %></td>
        <td><%= link_to 'Show', size %></td>
        <td><%= link_to 'Edit', edit_size_path(size) %></td>
        <td><%= link_to 'Destroy', size, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Size', new_size_path %>

app/views/sizes/new.html.erb
<h1>New size</h1>

<%= render 'form' %>

<%= link_to 'Back', sizes_path %>

app/views/sizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @size.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @size.code %>
</p>

<p>
  <strong>Category:</strong>
  <%= @size.category %>
</p>

<%= link_to 'Edit', edit_size_path(@size) %> |
<%= link_to 'Back', sizes_path %>