config/routes.rb
ShopShine::Application.routes.draw do

root to: 'authentications#new'

  namespace :api do
    resources :users
  end

  namespace :api do
    resources :category_sizes
  end

  namespace :api do
    resources :category
  end

  resources :authentications

  post 'users/category_sizes' => 'users#category_sizes'

  get 'users/results' => 'users#results'

  get 'users/results/:id' => 'users#results'

  get 'users/category_sizes/:categorysizeid' => 'users#show_json'

  resources :users

  get 'categories/show_json/:id' => 'categories#show_json'

  get 'signup' => 'users#new'

  resources :sizes

  resources :category_sizes

  resources :categories

  

  

end

app/controllers/api/category_sizes_controller.rb
class API::CategorySizesController < ApplicationController
	def index
    @category_sizes = CategorySize.all
    respond_to do |format|
      format.json { render :json => @category_sizes }
    end
  end

end

app/controllers/category_sizes_controller.rb
class CategorySizesController < ApplicationController
  before_action :set_category_size, only: [:show, :edit, :update, :destroy]

  # GET /category_sizes
  # GET /category_sizes.json
  def index
    @category_sizes = CategorySize.all
  end

  # GET /category_sizes/1
  # GET /category_sizes/1.json
  def show
    # @user = User.find(params[:id])
    @category_sizes = CategorySize.all
    # CategorySize.query_shopify(size_params)
  end

  # GET /category_sizes/new
  def new
    @category_size = CategorySize.new
  end

  # GET /category_sizes/1/edit
  def edit
  end

  # POST /category_sizes
  # POST /category_sizes.json
  def create
    @category_size = CategorySize.new(category_size_params)

    respond_to do |format|
      if @category_size.save
        format.html { redirect_to @category_size, notice: 'Category size was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category_size }
      else
        format.html { render action: 'new' }
        format.json { render json: @category_size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_sizes/1
  # PATCH/PUT /category_sizes/1.json
  def update
    respond_to do |format|
      if @category_size.update(category_size_params)
        format.html { redirect_to @category_size, notice: 'Category size was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category_size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_sizes/1
  # DELETE /category_sizes/1.json
  def destroy
    @category_size.destroy
    respond_to do |format|
      format.html { redirect_to category_sizes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_size
      @category_size = CategorySize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_size_params
      params.require(:category_size).permit(:category_id, :size_id)
    end
end

app/helpers/category_sizes_helper.rb
module CategorySizesHelper
end

app/views/category_sizes/_form.html.erb
<%= form_for(@category_size) do |f| %>
  <% if @category_size.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_size.errors.count, "error") %> prohibited this category_size from being saved:</h2>

      <ul>
      <% @category_size.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_sizes/edit.html.erb
<h1>Editing category_size</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_size %> |
<%= link_to 'Back', category_sizes_path %>

app/views/category_sizes/index.html.erb
<h1>Listing category_sizes</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @category_sizes.each do |category_size| %>
      <tr>
        <td><%= category_size.category.code %></td>
        <td><%= category_size.size.code %></td>
        <td><%= link_to 'Show', category_size %></td>
        <td><%= link_to 'Edit', edit_category_size_path(category_size) %></td>
        <td><%= link_to 'Destroy', category_size, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category size', new_category_size_path %>

app/views/category_sizes/new.html.erb
<h1>New category_size</h1>

<%= render 'form' %>

<%= link_to 'Back', category_sizes_path %>

app/views/category_sizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category_size.category %>
</p>

<p>
  <strong>Size:</strong>
  <%= @category_size.size %>
</p>

<%= link_to 'Edit', edit_category_size_path(@category_size) %> |
<%= link_to 'Back', category_sizes_path %>