config/routes.rb
ShopShine::Application.routes.draw do

root to: 'authentications#new'

  namespace :api do
    resources :users
  end

  namespace :api do
    resources :category_sizes
  end

  namespace :api do
    resources :category
  end

  resources :authentications

  post 'users/category_sizes' => 'users#category_sizes'

  get 'users/results' => 'users#results'

  get 'users/results/:id' => 'users#results'

  get 'users/category_sizes/:categorysizeid' => 'users#show_json'

  resources :users

  get 'categories/show_json/:id' => 'categories#show_json'

  get 'signup' => 'users#new'

  resources :sizes

  resources :category_sizes

  resources :categories

  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :parent, :class_name => 'Category',
  	foreign_key: 'category_id'
  has_many :sub_categories, :class_name => 'Category',
    foreign_key: 'category_id'
  has_many :sizes, through: :category_sizes, source: :size
  has_many :category_sizes




end

app/controllers/api/categories_controller.rb
class API::CategoriesController < ApplicationController
	def index
    @categories = Category.all
    respond_to do |format|
      format.json { render :json => @categories }
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where("code IS NOT NULL")
  end

  def show_json
    render json: (HTTParty.get("http://api.shopstyle.com/api/v2/products?pid=uid6596-24043686-75&fts=mens-jeans&amp;fl=s120"))
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :code, :category_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<%= collection_select :category, :category, @categories, :id, :name %>

<script>
//only after the page is fully loaded so we so any part of this
  $(function(){

    var c = $("#category_category");

    c.prepend("<option>SELECT A CHOICE</option>");
    c[0].selectedIndex = 0;

    c.change(function(){
        // Stuff to do when the grop-down changes
      $.get("categories/show_json/" + c.val(), showCoolData)

    });

  });

  function showCoolData(data){
    alert(data);
  }
</script>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @category.code %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>